apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: tcc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: tcc-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-app
  namespace: tcc
spec:
  selector:
    matchLabels:
      app: tcc-app
  template:
    metadata:
      labels:
        app: tcc-app
    spec:
      containers:
        - name: tcc-app
          image: 1_cenario_docker-app:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: appuser
            - name: DB_PASS
              value: apppass
            - name: DB_NAME
              value: appdb
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
